### ISSUE TITLE
MCC: Article (5/19)

### ISSUE THREAD

**Issue by mccurcio** [studydash/cards#52]
## Today's Goal/Solution 🥅:
Write up an article for beginners and place it on Codenewbie
---

## Result 🍓🍌🍉:
1st Draft finished

---

## Observations & Next Steps 🔭👣:
My goal in the near future is to convert some of my writings to small articles for posting on dev.to and hashnode.

**Comment by r002** [comment]
Blogging and posting on `dev.to` and `hashnode` is a great idea!  I look forward to reading your writings!  👍

**Also:**  Oh no, Matt!!!!!!!!!!!  You didn't submit this yesterday so the system now counts `Wed, 5/19` as a `Missed Day` and resets your streak. 😥  Since everything is automated now, [the dashboard](https://r002.github.io/codenewbie/qa) automatically categorizes all cards based on their `Creation Date`.  The dashboard doesn't care how many times you update a card (it can even be a different day) so what I often do is create my card in the morning and then update it multiple times throughout the day as I make progress.  I rely on each card as a kinda `Notes to Self` so I find the system actually works quite well.  ☺  Also, feel free to modify the default template to suit your needs-- the default was just something I quickly threw together at the time.  But since everyone's studying/working on something different, it's sensible that everyone's cards will have different structures.

No worries though-- as I was pondering this more this morning, I think it makes sense that every study group member gets two `free passes` each month.  Eg.  If you miss a day, you then have the option to "use a pass" for the missed day.  Idk, just still kicking around ideas!  Gamifying GitHub is fun!! 😄

See you this afternoon at our check-in!  🙋‍♂️

![image](https://user-images.githubusercontent.com/45280066/119004713-ca792980-b95c-11eb-9016-2e6c3515839c.png)

**Comment by mccurcio** [comment]
Hey R,
Are we still on for today at 2PM.

Delete this after you read it. ;D
**https://meet.google.com/syh-cnta-tqi**

**Comment by r002** [comment]
Hi Matt!  Yup, did you receive my calendar invite?  2p ET today.

**Comment by r002** [comment]
Hi Matt!  Great catching up with you today!  Thank you for making time! 😀

Btw, after we ended the call, I investigated why you were receiving just a weird "black page."

Are you by chance using Firefox?  When I try loading [the dashboard](https://r002.github.io/codenewbie/qa) on Firefox on my machine, I get:

![image](https://user-images.githubusercontent.com/45280066/119048869-d3362380-b98d-11eb-80f8-6a8dcf0bc925.png)

It's bc I'm using `private fields` in a JS class which isn't supported in `Firefox` yet.  `Private fields` is a new spec [that just got approved last month in April](https://github.com/tc39/proposals/blob/master/finished-proposals.md) (reached [Stage 4](https://tc39.es/process-document/)) and so it appears like [Firefox doesn't yet support it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#browser_compatibility).

![image](https://user-images.githubusercontent.com/45280066/119051326-05955000-b991-11eb-9f22-eff6bf804d57.png)

When you get a chance, can you please try loading [the dashboard](https://r002.github.io/codenewbie/qa) in another browser and lmk if that works for you?  Thank you! 🙏

**Comment by mccurcio** [comment]
Firefox, you are correct!

Thank you,

Matt Curcio
M: 401-316-5358
W: https://github.com/mccurcio

-----------------------------------------
What you think, you become.
What you imagine, you create.

Gautama Buddha
-----------------------------------------

**Comment by r002** [comment]
Awesome, good to confirm!  Thanks for checking!  🙏

I'm currently not using `private fields` for anything overly important in my current implementation of the `dashboard`.
So once I have some extra time, I'll strip them from the code (can just replace `#` with `_`, more-or-less) and it should be fine.

Btw-- is there a specific reason you use Firefox?  Just muscle memory/habit?  Or is there a particular feature unique in FF that you like/need?  Genuinely curious!

**Comment by anitabe404** [comment]
I want to post articles on dev.to as well, but I find it takes me *forever* to write anything that I like. I have a bunch of stuff in various states of unfinished. 😂

**Comment by mccurcio** [comment]
I have so much old stuff too but I said **dam-it-do-it**
I feel my article is for idiots (mainly) because I wrote but
on-ward-and-upward.

AND a recruiter told me "you HAVE to blog and place articles on Linkedin".

So I am yielding to the Force.
😎🤔
